add_compile_definitions(
    DSP_IMAGE_COPY_TO_RAM=1
    XA_MP3_DECODER=1
    CPU_MIMXRT595SFFOB
    CPU_MIMXRT595SFFOB_cm33
    BOOT_HEADER_ENABLE=1
    FSL_SDK_DRIVER_QUICK_ACCESS_ENABLE=1
    BOARD_ENABLE_PSRAM_CACHE=0
    SSD1963_DATA_WITDH=8
    FLEXIO_MCULCD_DATA_BUS_WIDTH=8
    DBI_FLEXIO_USE_SMARTDMA=1
    # SDK_DEBUGCONSOLE_UART
    VG_RESOLVE_ENGINE=0
    VG_PE_COLOR_KEY=0
    VG_IM_INDEX_FORMAT=0
    VG_AYUV_INPUT_OUTPUT=0
    VG_DOUBLE_IMAGE=0
    VG_RECTANGLE_STRIP_MODE=0
    VG_MMU=0
    VG_IM_FILTER=0
    VG_IM_YUV_PACKET=1
    VG_IM_YUV_PLANAR=0
    VG_PE_YUV_PACKET=1
    VG_TARGET_TILED=1
    VG_COMMAND_CALL=1
    VG_SHARE_BUFFER_IM_16K=0
    VG_OFFLINE_MODE=0
    VG_RESOLUTION_2880=0
    VG_PE_PREMULTIPLY=0
    VG_POST_CONVERTER=0
    VG_PRE_CONVERTER=0
    VG_RENDER_BY_MESH=0
    VG_TARGET_FAST_CLEAR=0
    VG_BUFFER_NUMBER_OF_TARGET=0
    VG_VIDEO_CLEAR_CONTROL=0
    VG_VIDEO_CONTROL=0
    VGLITE_TST_FIRMWARE=0
    VG_LITE_SYS_GPU_CTRL=0
    RTOS
    SERIAL_PORT_TYPE_SWO=0
    FSL_RTOS_FREE_RTOS
    # SDK_DEBUGCONSOLE=1
    CR_INTEGER_PRINTF
    PRINTF_FLOAT_ENABLE=0
    __MCUXPRESSO
    __USE_CMSIS
    DEBUG
    __NEWLIB__
    SDK_I2C_BASED_COMPONENT_USED=1
    SERIAL_PORT_TYPE_UART=1
    CUSTOM_VGLITE_MEMORY_CONFIG=1
    _VG_LITE_IRQ_CALLBACK=1
    SIDEKICK_PROJECT=1
    FX_PLATFORM_ARM_M33
    FT2_BUILD_LIBRARY
    AFE4500_TEST_FUNCTION
    FACTORY_PROJECT=1
)

include_directories(
    "${PROJECT_DIR}/Sources/Configs"
    "${PROJECT_DIR}/Sources/Configs/gen7_factory"
    "${PROJECT_DIR}/Sources/Modules/dsp/dsp_manager"
    "${PROJECT_DIR}/Sources/Modules/dsp/dsp_audio"
    "${PROJECT_DIR}/Sources/HAL/hal_dsp"
    "${PROJECT_DIR}/Third_Parties/NXP/SDK/rtos/freertos/freertos_kernel/portable/GCC/ARM_CM33_NTZ/non_secure"
    "${PROJECT_DIR}/Third_Parties/NXP/SDK/rtos/freertos/freertos_kernel/include"
    "${PROJECT_DIR}/Third_Parties/NXP/SDK/CMSIS"
    "${PROJECT_DIR}/Third_Parties/NXP/SDK/devices/MIMXRT595S/drivers"
    "${PROJECT_DIR}/Third_Parties/NXP/SDK/devices/MIMXRT595S/utilities"
    "${PROJECT_DIR}/Third_Parties/NXP/SDK/devices/MIMXRT595S/utilities/debug_console"
    "${PROJECT_DIR}/Third_Parties/NXP/SDK/devices/MIMXRT595S/utilities/str"
    "${PROJECT_DIR}/Third_Parties/NXP/SDK/components/video"
    "${PROJECT_DIR}/Third_Parties/NXP/SDK/components/ssd1963"
    "${PROJECT_DIR}/Third_Parties/NXP/SDK/components/ft3267"
    "${PROJECT_DIR}/Third_Parties/NXP/SDK/components/lists"
    "${PROJECT_DIR}/Third_Parties/NXP/SDK/components/serial_manager"
    "${PROJECT_DIR}/Third_Parties/NXP/SDK/components/uart"
    "${PROJECT_DIR}/Third_Parties/NXP/SDK/components/pca9420"
    "${PROJECT_DIR}/Sources/Configs/board"
    "${PROJECT_DIR}/Sources/Configs/device"
    "${PROJECT_DIR}/Sources/Configs/flash_config"
    "${PROJECT_DIR}/Third_Parties/NXP/SDK/middleware/elementary/inc"
    "${PROJECT_DIR}/Third_Parties/NXP/SDK/middleware/elementary/src"
    "${PROJECT_DIR}/Third_Parties/NXP/SDK/middleware/multicore/rpmsg_lite/lib/include"
    "${PROJECT_DIR}/Third_Parties/NXP/SDK/middleware/multicore/rpmsg_lite/lib/include/platform/imxrt500_m33"
    "${PROJECT_DIR}/Third_Parties/NXP/SDK/middleware/fatfs/source"
    "${PROJECT_DIR}/Third_Parties/NXP/SDK/middleware/fatfs/template"
    "${PROJECT_DIR}/Third_Parties/NXP/SDK/middleware/fatfs/source/fsl_ram_disk"
    "${PROJECT_DIR}/Third_Parties/NXP/SDK/middleware/fatfs/source/fsl_nor_disk"
    "${PROJECT_DIR}/Third_Parties/NXP/SDK/devices/MIMXRT595S"
    "${PROJECT_DIR}/Sources/Drivers/pmic_driver"
    "${PROJECT_DIR}/Sources/Modules/os_wrapper"
    "${PROJECT_DIR}/Sources/Modules/os_wrapper/FreeRTOS"
    "${PROJECT_DIR}/Sources/HAL/msf_hal"
    "${PROJECT_DIR}/Sources/HAL/hal_i2c"
    "${PROJECT_DIR}/Sources/HAL/hal_i2s"
    "${PROJECT_DIR}/Sources/HAL/hal_spi"
    "${PROJECT_DIR}/Sources/HAL/hal_uart"
    "${PROJECT_DIR}/Sources/HAL/hal_delay"
    "${PROJECT_DIR}/Sources/HAL/hal_gpio"
    "${PROJECT_DIR}/Sources/HAL/hal_power_control"
    "${PROJECT_DIR}/Sources/Modules/msf_assert"
    "${PROJECT_DIR}/Sources/Drivers/flexspi_flash"
    "${PROJECT_DIR}/Sources/Modules/common_pool"
    "${PROJECT_DIR}/Sources/Modules/cts"
    "${PROJECT_DIR}/Sources/Modules/fossil_file_system"
    "${PROJECT_DIR}/Sources/Modules/isr_thread"
    "${PROJECT_DIR}/Sources/Modules/msf_handler"
    "${PROJECT_DIR}/Sources/Modules/pds"
    "${PROJECT_DIR}/Sources/Modules/pub_sub"
    "${PROJECT_DIR}/Sources/Modules/sensor"
    "${PROJECT_DIR}/Sources/Modules/sensor/sensor_adapter"
    "${PROJECT_DIR}/Sources/Modules/sensor/sensor_service"
    "${PROJECT_DIR}/Sources/Modules/utility"
    "${PROJECT_DIR}/Sources/Modules/msf_timer"
    "${PROJECT_DIR}/Sources/Modules/clock_time"
    "${PROJECT_DIR}/Sources/Modules/cypress"
    "${PROJECT_DIR}/Sources/Modules/app_open_demo"
    "${PROJECT_DIR}/Sources/Drivers/accel/accel_dev"
    "${PROJECT_DIR}/Sources/Drivers/accel/accel_drv"
    "${PROJECT_DIR}/Sources/Drivers/afe4500"
    "${PROJECT_DIR}/Sources/Drivers/ambient_light"
    "${PROJECT_DIR}/Sources/Drivers/ambient_light/ltr308"
    "${PROJECT_DIR}/Sources/Drivers/display"
    "${PROJECT_DIR}/Sources/Drivers/touch/radium"
    "${PROJECT_DIR}/Third_Parties/exactle/ble-host/include"
    "${PROJECT_DIR}/Third_Parties/exactle/ble-host/sources/hci/nxp/rt500"
    "${PROJECT_DIR}/Third_Parties/exactle/ble-host/sources/hci/nxp"
    "${PROJECT_DIR}/Third_Parties/exactle/ble-host/sources/sec/common"
    "${PROJECT_DIR}/Third_Parties/exactle/ble-host/sources/stack/att"
    "${PROJECT_DIR}/Third_Parties/exactle/ble-host/sources/stack/cfg"
    "${PROJECT_DIR}/Third_Parties/exactle/ble-host/sources/stack/dm"
    "${PROJECT_DIR}/Third_Parties/exactle/ble-host/sources/stack/hci"
    "${PROJECT_DIR}/Third_Parties/exactle/ble-host/sources/stack/l2c"
    "${PROJECT_DIR}/Third_Parties/exactle/ble-host/sources/stack/smp"
    "${PROJECT_DIR}/Third_Parties/exactle/ble-profiles/sources/services"
    "${PROJECT_DIR}/Third_Parties/exactle/wsf/include"
    "${PROJECT_DIR}/Third_Parties/exactle/wsf/sources/port/freertos"
    "${PROJECT_DIR}/Third_Parties/exactle/wsf/sources"
    "${PROJECT_DIR}/Third_Parties/uecc"
    "${PROJECT_DIR}/Sources/Modules/ble/ble_app/ble_profiles"
    "${PROJECT_DIR}/Sources/Modules/ble/ble_app/ble_ams"
    "${PROJECT_DIR}/Sources/Modules/ble/ble_app/ble_cts"
    "${PROJECT_DIR}/Sources/Modules/ble/ble_app/ble_diag"
    "${PROJECT_DIR}/Sources/Modules/ble/ble_app/ble_ft"
    "${PROJECT_DIR}/Sources/Modules/ble/ble_app/ble_media"
    "${PROJECT_DIR}/Sources/Modules/ble/ble_app/ble_msf"
    "${PROJECT_DIR}/Sources/Modules/ble/ble_app/ble_time"
    "${PROJECT_DIR}/Sources/Modules/ble/ble_app/ble_notif"
    "${PROJECT_DIR}/Sources/Modules/ble/ble_app/ble_ancs"
    "${PROJECT_DIR}/Sources/Modules/ble/ble_core/ble_db"
    "${PROJECT_DIR}/Sources/Modules/ble/ble_core/ble_gap"
    "${PROJECT_DIR}/Sources/Modules/ble/ble_core/ble_gatt"
    "${PROJECT_DIR}/Sources/Modules/ble/ble_core/ble_hci"
    "${PROJECT_DIR}/Sources/Modules/ble/ble_core/ble_sal"
    "${PROJECT_DIR}/Sources/Modules/ble/ble_core/ble_svc"
    "${PROJECT_DIR}/Sources/Modules/ble/ble_core/ble_task"
    "${PROJECT_DIR}/Sources/Modules/ble/ble_core/ble_utils"
    "${PROJECT_DIR}/Sources/Modules/ble/ble_core/include"
    "${PROJECT_DIR}/Sources/Modules/ble/ble_thread"
    "${PROJECT_DIR}/Sources/Modules/file_transfer/ft_file"
    "${PROJECT_DIR}/Sources/Modules/file_transfer/ft_cmd"
    "${PROJECT_DIR}/Sources/Modules/file_transfer/ft_evt"
    "${PROJECT_DIR}/Sources/Modules/file_transfer/ft_socket"
    "${PROJECT_DIR}/Sources/Modules/file_transfer/ft_log"
    "${PROJECT_DIR}/Sources/Modules/file_transfer/ft_security"
    "${PROJECT_DIR}/Sources/Modules/file_transfer/include"
    "${PROJECT_DIR}/Third_Parties/exactle/wsf/sources/util"
    "${PROJECT_DIR}/Sources/Modules/config_file"
    "${PROJECT_DIR}/Sources/Modules/info_file"
    "${PROJECT_DIR}/Sources/Modules/ffs_file_transfer"
    "${PROJECT_DIR}/Sources/Modules/watch_dog"
    "${PROJECT_DIR}/Sources/Modules/display_thread"
    "${PROJECT_DIR}/Sources/Modules/sidekick_display"
    "${PROJECT_DIR}/Sources/Modules/png_decoder"
    "${PROJECT_DIR}/Third_Parties/libpng"
    "${PROJECT_DIR}/Sources/Modules/algorithm_thread"
    "${PROJECT_DIR}/Sources/Modules/algorithms"
    "${PROJECT_DIR}/Sources/Modules/algorithms/allocator"
    "${PROJECT_DIR}/Sources/Modules/algorithms/assert"
    "${PROJECT_DIR}/Sources/Modules/algorithms/buffer"
    "${PROJECT_DIR}/Sources/Modules/algorithms/c_linked_list"
    "${PROJECT_DIR}/Sources/Modules/algorithms/factory"
    "${PROJECT_DIR}/Sources/Modules/algorithms/filter"
    "${PROJECT_DIR}/Sources/Modules/algorithms/hsm"
    "${PROJECT_DIR}/Sources/Modules/algorithms/include"
    "${PROJECT_DIR}/Sources/Modules/algorithms/internal"
    "${PROJECT_DIR}/Sources/Modules/algorithms/math_helper_generic"
    "${PROJECT_DIR}/Sources/Modules/algorithms/resampler"
    "${PROJECT_DIR}/Sources/Modules/algorithms/step"
    "${PROJECT_DIR}/Sources/Modules/algorithms/tap"
    "${PROJECT_DIR}/Sources/Modules/ui/watch_face"
    "${PROJECT_DIR}/Sources/Modules/linked_list"
    "${PROJECT_DIR}/Sources/Drivers/accel_gyros/accel_gyros_dev"
    "${PROJECT_DIR}/Sources/Drivers/accel_gyros/accel_gyros_drv"
    "${PROJECT_DIR}/Sources/Drivers/dmic"
    "${PROJECT_DIR}/Sources/Modules/audio_thread"
    "${PROJECT_DIR}/Sources/Drivers/audio_codec/wm8904"
    "${PROJECT_DIR}/Third_Parties/NXP/SDK/components/i2c"
    "${PROJECT_DIR}/Sources/Drivers/audio_codec"
    "${PROJECT_DIR}/Third_Parties/microej/thirdparty/systemview/inc"
    "${PROJECT_DIR}/Third_Parties/microej/thirdparty/systemview-freertos/inc"
    "${PROJECT_DIR}/Third_Parties/NXP/SDK/middleware/emwin/emWin_Config"
    "${PROJECT_DIR}/Third_Parties/NXP/SDK/middleware/emwin/emWin_header"
    "${PROJECT_DIR}/Third_Parties/microej/source/freetype/inc"
    "${PROJECT_DIR}/Third_Parties/microej/source/kf/inc"
    "${PROJECT_DIR}/Third_Parties/microej/source/lowpower/inc"
    "${PROJECT_DIR}/Third_Parties/microej/source/main/inc"
    "${PROJECT_DIR}/Third_Parties/microej/source/trace/inc"
    "${PROJECT_DIR}/Third_Parties/microej/source/ui/inc"
    "${PROJECT_DIR}/Third_Parties/microej/source/util/inc"
    "${PROJECT_DIR}/Third_Parties/microej/platform/inc"
    "${PROJECT_DIR}/Third_Parties/microej/platform/inc/intern"
    "${PROJECT_DIR}/Third_Parties/microej/middleware/vglite/inc"
    "${PROJECT_DIR}/Third_Parties/microej/middleware/vglite/VGLite"
    "${PROJECT_DIR}/Third_Parties/microej/middleware/vglite/VGLite/rtos"
    "${PROJECT_DIR}/Third_Parties/microej/middleware/vglite/VGLiteKernel"
    "${PROJECT_DIR}/Third_Parties/microej/middleware/vglite/VGLiteKernel/rtos"
    "${PROJECT_DIR}/Third_Parties/microej/source/vg/inc"
    "${PROJECT_DIR}/Third_Parties/microej/source/vglite_support"
    "${PROJECT_DIR}/Third_Parties/microej/source/vglite_window"
    "${PROJECT_DIR}/Sources/Modules/fsbus_interface"
    "${PROJECT_DIR}/Sources/Drivers/fsbus"
    "${PROJECT_DIR}/Third_Parties/protobuf-c/protobuf-c"
    "${PROJECT_DIR}/Third_Parties/protobuf-c"
    "${PROJECT_DIR}/Third_Parties/"
    "${PROJECT_DIR}/Sources/Proto/c_out/root"
    "${PROJECT_DIR}/Sources/Proto/c_out/fsbus"
    "${PROJECT_DIR}/Sources/Proto/c_out"
    "${PROJECT_DIR}/Sources/Proto/c_out/root_file"
    "${PROJECT_DIR}/Sources/Proto/c_out/microej"
    "${PROJECT_DIR}/Sources/Drivers/pah_driver/pah_main"
    "${PROJECT_DIR}/Sources/Drivers/pah_driver/pah813x_driver"
    "${PROJECT_DIR}/Sources/Drivers/pah_driver/pah"
    "${PROJECT_DIR}/Sources/Drivers/barometer"
    "${PROJECT_DIR}/Sources/Drivers/barometer/bmp388"
    "${PROJECT_DIR}/Sources/Modules/algorithms/ohr"
    "${PROJECT_DIR}/Sources/Modules/ohr/firstbeat"
    "${PROJECT_DIR}/Sources/Modules/algorithms/ohr/fx_lib"
    "${PROJECT_DIR}/Sources/Modules/ohr/hr_profile"
    "${PROJECT_DIR}/Sources/Modules/algorithms/ohr/ohr_mode_switch"
    "${PROJECT_DIR}/Sources/Modules/sidekick_resource_man"
    "${PROJECT_DIR}/Sources/Modules/display_manager"
    "${PROJECT_DIR}/Sources/Drivers/ecompass"
    "${PROJECT_DIR}/Sources/Drivers/rotary"
    "${PROJECT_DIR}/Sources/Drivers/rotary/pat9128ja"
    "${PROJECT_DIR}/Sources/Modules/sensor_service"
    "${PROJECT_DIR}/Sources/Modules/input_device_thread"
    "${PROJECT_DIR}/Sources/Modules/oad"
    "${PROJECT_DIR}/Sources/Modules/fw_update"
    "${PROJECT_DIR}/Sources/Drivers/gps"
    "${PROJECT_DIR}/Sources/Modules/gps_thread"
    "${PROJECT_DIR}/Sources/HAL/hal_adc"
    "${PROJECT_DIR}/Sources/Modules/power_mode"
    "${PROJECT_DIR}/Sources/Drivers/button"
    "${PROJECT_DIR}/Sources/Modules/bt_passthrough"
    "${PROJECT_DIR}/Sources/Modules/display_manager/lcd_brightness/auto_brightness_controller"
    "${PROJECT_DIR}/Sources/Modules/display_manager/lcd_brightness/brightness_animator"
    "${PROJECT_DIR}/Third_Parties/mbedtls-2.6.0/include"
    "${PROJECT_DIR}/Sources/Modules/device_security"
    "${PROJECT_DIR}/Sources/Modules/pb_file"
    "${PROJECT_DIR}/Sources/Modules/flat_file_transfer"
    "${PROJECT_DIR}/Sources/Modules/hw_logger/src"
    "${PROJECT_DIR}/Sources/Modules/activity_logger/src"
    "${PROJECT_DIR}/Sources/Modules/log_manager"
    "${PROJECT_DIR}/Sources/Modules/log_writer"
    "${PROJECT_DIR}/Sources/Modules/main/main_factory"
    "${PROJECT_DIR}/Sources/Modules/background_sync"
    "${PROJECT_DIR}/Sources/Modules/notification_filter"
    "${PROJECT_DIR}/Sources/Modules/fitness_tracker"
    "${PROJECT_DIR}/Sources/Modules/device_factory_reset"
    "${PROJECT_DIR}/Sources/Modules/ble/ble_app_heartbeat"
    "${PROJECT_DIR}/Sources/Modules/fsl_workout"
    "${PROJECT_DIR}/Sources/Drivers/i2s_switch"
    "${PROJECT_DIR}/Sources/Drivers/i2s_switch/ice40lp"
    "${PROJECT_DIR}/Sources/Modules/boot_state"
    "${PROJECT_DIR}/Sources/Drivers/audio_codec/tfa9897"
    "${PROJECT_DIR}/Sources/Drivers/audio_codec/tfa9897/image"
    "${PROJECT_DIR}/Sources/Modules/audio_manager/"
    "${PROJECT_DIR}/Sources/Modules/audio_manager/chunk_data_hdrs"
    "${PROJECT_DIR}/Sources/Modules/audio_manager/chunk_data_hdrs/rcv_audio_chunk_thread"
    "${PROJECT_DIR}/Sources/Modules/audio_manager/chunk_data_hdrs/process_audio_chunk_thread"
    "${PROJECT_DIR}/Sources/Modules/audio_manager/audio_test_thread"
    "${PROJECT_DIR}/Sources/Modules/conversa"
    "${PROJECT_DIR}/Sources/Modules/audio_manager/micro_recorder"
    "${PROJECT_DIR}/Sources/Modules/voice_recognition"
    "${PROJECT_DIR}/Third_Parties/microej/thirdparty/freetype/inc"
    "${PROJECT_DIR}/Third_Parties/microej/thirdparty/freetype/inc/freetype/config"
    "${PROJECT_DIR}/Third_Parties/microej/thirdparty/libwebp"
    "${PROJECT_DIR}/Third_Parties/microej/source/fs/inc"
    "${PROJECT_DIR}/Third_Parties/microej/source/fs/src"
    "${PROJECT_DIR}/Sources/Drivers/fuel_gauge"
    "${PROJECT_DIR}/Sources/Modules/sync_service"
    "${PROJECT_DIR}/Sources/Modules/serialize_data"
    "${PROJECT_DIR}/Sources/Modules/algorithms/logistic_regression"
    "${PROJECT_DIR}/Sources/Modules/algorithms/calorie_calculator"
    "${PROJECT_DIR}/Sources/Modules/algorithms/accel_adapter"
    "${PROJECT_DIR}/Sources/HAL/hal_dsp/binaries/xaf"
    "${PROJECT_DIR}/Sources/HAL/hal_dsp/binaries/vit"
    "${PROJECT_DIR}/Sources/HAL/hal_dsp/binaries/conversa"
    "${PROJECT_DIR}/Sources/HAL/hal_io_config"
    "${PROJECT_DIR}/Sources/Drivers/vibe_driver"
    "${PROJECT_DIR}/Sources/Drivers/vibe_driver/awinic"
    "${PROJECT_DIR}/Sources/Modules/anim_management"
    "${PROJECT_DIR}/Sources/Modules/std_vibe"
    "${PROJECT_DIR}/Sources/Modules/vibe"
    "${PROJECT_DIR}/Sources/Modules/hwtest"
    "${PROJECT_DIR}/Sources/Modules/hwtest/hwtest_cpnt"
    "${PROJECT_DIR}/Sources/Modules/factory_test"
)

set(PROJ_FLAGS "-fno-common -fmessage-length=0 -fstack-reuse=none -fmerge-constants -fmacro-prefix-map=\"$(<D)/\"= -mcpu=cortex-m33 -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -D__NEWLIB__ -fstack-usage -MMD -MP -MF\"$(@:%.o=%.d)\" -MT\"$(@:%.o=%.o)\" -MT\"$(@:%.o=%.d)\"")
set(CMAKE_C_FLAGS  "${CMAKE_C_FLAGS} ${PROJ_FLAGS}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${PROJ_FLAGS}")
set(CMAKE_ASM_FLAGS "${CMAKE_ASM_FLAGS} ${PROJ_FLAGS}")
